''' This script is used to generate some sources '''

import glob

def generate_values_all_h():
    l = glob.glob('values/*.hpp')

    with open('values/All.hpp', 'w') as writer:
        for f in l:
            part = f.split('/')[-1]
            if not part.startswith('Value'): continue
            writer.write('#include "%s"\n' % part)

        writer.write('\n// generated by Python script')

if __name__ == '__main__':
    generate_values_all_h()
